export const sharedCatalog = [
  {
    "id": "shared-0",
    "title": "3D Digital Twin",
    "category": "产品介绍",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/3D Digital Twin.pdf",
    "location": "Brochure",
    "updated": "2026-08-12"
  },
  {
    "id": "shared-1",
    "title": "BMS Funciton Brochure 2505",
    "category": "产品介绍",
    "format": "PDF",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/BMS Funciton Brochure 2505.pdf",
    "location": "Brochure",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-2",
    "title": "CCCS Function Brochure 2505",
    "category": "产品介绍",
    "format": "PDF",
    "product": "CCCS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/CCCS Function Brochure 2505.pdf",
    "location": "Brochure",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-3",
    "title": "CET BMS Catalog",
    "category": "产品介绍",
    "format": "PDF",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/CET BMS Catalog.pdf",
    "location": "Brochure",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-4",
    "title": "CET PQMS Catalog",
    "category": "产品介绍",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/CET PQMS Catalog.pdf",
    "location": "Brochure",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-5",
    "title": "DCIM Function Brochure 2505",
    "category": "产品介绍",
    "format": "PDF",
    "product": "DCIM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/DCIM Function Brochure 2505.pdf",
    "location": "Brochure",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-6",
    "title": "EPMS Function Brochure 2509",
    "category": "产品介绍",
    "format": "PDF",
    "product": "EPMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/EPMS Function Brochure 2509.pdf",
    "location": "Brochure",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-7",
    "title": "bMS Function Brochure 2509",
    "category": "产品介绍",
    "format": "PDF",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/bMS Function Brochure 2509.pdf",
    "location": "Brochure",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-8",
    "title": "BMS_Function_Brochure_Part1",
    "category": "产品介绍",
    "format": "PDF",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/catalog源文件/BMS_Function_Brochure_Part1.pdf",
    "location": "Brochure/catalog源文件",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-9",
    "title": "BMS_Function_Brochure_Part2",
    "category": "产品介绍",
    "format": "PDF",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/catalog源文件/BMS_Function_Brochure_Part2.pdf",
    "location": "Brochure/catalog源文件",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-10",
    "title": "CCCS",
    "category": "产品介绍",
    "format": "PDF",
    "product": "CCCS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/catalog源文件/CCCS.pdf",
    "location": "Brochure/catalog源文件",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-11",
    "title": "CCCS_Brochure",
    "category": "产品介绍",
    "format": "PDF",
    "product": "CCCS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/catalog源文件/CCCS_Brochure.pdf",
    "location": "Brochure/catalog源文件",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-12",
    "title": "BA3.0",
    "category": "产品介绍",
    "format": "DOCX",
    "product": "BA",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/彩页资料/BA3.0.docx",
    "location": "Brochure/彩页资料",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-13",
    "title": "BMS-3.0资料",
    "category": "产品介绍",
    "format": "DOCX",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/彩页资料/BMS-3.0资料.docx",
    "location": "Brochure/彩页资料",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-14",
    "title": "DCIM-3.0",
    "category": "产品介绍",
    "format": "DOCX",
    "product": "DCIM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/彩页资料/DCIM-3.0.docx",
    "location": "Brochure/彩页资料",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-15",
    "title": "EPMS图片资料",
    "category": "产品介绍",
    "format": "DOCX",
    "product": "EPMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/彩页资料/EPMS图片资料.docx",
    "location": "Brochure/彩页资料",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-16",
    "title": "EPMS资料",
    "category": "产品介绍",
    "format": "DOCX",
    "product": "EPMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Brochure/彩页资料/EPMS资料.docx",
    "location": "Brochure/彩页资料",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-17",
    "title": "CET-DC Info V2026 (Jun.01)",
    "category": "演示材料",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/CET-DC Info V2026 (Jun.01)/CET-DC Info V2026 (Jun.01).pdf",
    "location": "PPT/CET-DC Info V2026 (Jun.01)",
    "updated": "2026-07-13"
  },
  {
    "id": "shared-18",
    "title": "CET-DC Info V2026 (Jun.01)",
    "category": "演示材料",
    "format": "PPTX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/CET-DC Info V2026 (Jun.01)/CET-DC Info V2026 (Jun.01).pptx",
    "location": "PPT/CET-DC Info V2026 (Jun.01)",
    "updated": "2026-07-13"
  },
  {
    "id": "shared-19",
    "title": "DCIM园区综合监控平台解决方案介绍-20241225",
    "category": "演示材料",
    "format": "PDF",
    "product": "DCIM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/国内/DCIM/DCIM园区综合监控平台解决方案介绍-20241225.pdf",
    "location": "PPT/国内/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-20",
    "title": "产品介绍PPT（面向销售版） IMC by hss 202507",
    "category": "演示材料",
    "format": "PPTX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/国内/DCIM/产品介绍PPT（面向销售版） IMC by hss 202507.pptx",
    "location": "PPT/国内/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-21",
    "title": "DCOM运营平台-v1.2",
    "category": "演示材料",
    "format": "PDF",
    "product": "DCOM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/国内/DCOM/DCOM运营平台-v1.2.pdf",
    "location": "PPT/国内/DCOM",
    "updated": "2026-09-08"
  },
  {
    "id": "shared-22",
    "title": "DCOM运营平台-v1.2",
    "category": "演示材料",
    "format": "PPTX",
    "product": "DCOM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/国内/DCOM/DCOM运营平台-v1.2.pptx",
    "location": "PPT/国内/DCOM",
    "updated": "2026-07-30"
  },
  {
    "id": "shared-23",
    "title": "云将数据中心运营平台v1.2",
    "category": "演示材料",
    "format": "PPTX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/国内/DCOM/云将数据中心运营平台v1.2.pptx",
    "location": "PPT/国内/DCOM",
    "updated": "2026-06-09"
  },
  {
    "id": "shared-24",
    "title": "深圳中电_DCOM介绍",
    "category": "演示材料",
    "format": "PDF",
    "product": "DCOM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/国内/DCOM/深圳中电_DCOM介绍.pdf",
    "location": "PPT/国内/DCOM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-25",
    "title": "深圳中电_DCOM介绍6",
    "category": "演示材料",
    "format": "PDF",
    "product": "DCOM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/国内/DCOM/深圳中电_DCOM介绍6.pdf",
    "location": "PPT/国内/DCOM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-26",
    "title": "深圳中电_DCOM介绍6",
    "category": "演示材料",
    "format": "PPTX",
    "product": "DCOM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/国内/DCOM/深圳中电_DCOM介绍6.pptx",
    "location": "PPT/国内/DCOM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-27",
    "title": "CET 数据中心楼宇管理系统介绍",
    "category": "演示材料",
    "format": "PPTX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/国内/其他/CET 数据中心楼宇管理系统介绍.pptx",
    "location": "PPT/国内/其他",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-28",
    "title": "CET数据中心解决方案-",
    "category": "演示材料",
    "format": "PPTX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/国内/其他/CET数据中心解决方案-.pptx",
    "location": "PPT/国内/其他",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-29",
    "title": "CET Data Centre BMS Solution",
    "category": "演示材料",
    "format": "PPTX",
    "product": "BMS",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/CET Data Centre BMS Solution.pptx",
    "location": "PPT/海外/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-30",
    "title": "CET PecStar Introduction",
    "category": "演示材料",
    "format": "PPTX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/CET PecStar Introduction.pptx",
    "location": "PPT/海外/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-31",
    "title": "CET-DC DCIM Jun 2026 En",
    "category": "演示材料",
    "format": "PDF",
    "product": "DCIM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/CET-DC DCIM Jun 2026 En.pdf",
    "location": "PPT/海外/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-32",
    "title": "CET-DC DCIM Jun 2026 En",
    "category": "演示材料",
    "format": "PPTX",
    "product": "DCIM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/CET-DC DCIM Jun 2026 En.pptx",
    "location": "PPT/海外/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-33",
    "title": "CET-DC Info V2025(Mar.26)",
    "category": "演示材料",
    "format": "PPTX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/CET-DC Info V2025(Mar.26).pptx",
    "location": "PPT/海外/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-34",
    "title": "CET-DC Info V2026 (Jun.01)",
    "category": "演示材料",
    "format": "PPTX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/CET-DC Info V2026 (Jun.01).pptx",
    "location": "PPT/海外/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-35",
    "title": "CET-DC Info V2026(Jan.07)",
    "category": "演示材料",
    "format": "PDF",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/CET-DC Info V2026(Jan.07).pdf",
    "location": "PPT/海外/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-36",
    "title": "CET-DC Info V2026(Jan.07)",
    "category": "演示材料",
    "format": "PPTX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/CET-DC Info V2026(Jan.07).pptx",
    "location": "PPT/海外/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-37",
    "title": "CET-iMCM DCIM Sep 2025 En",
    "category": "演示材料",
    "format": "PPTX",
    "product": "DCIM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/CET-iMCM DCIM Sep 2025 En.pptx",
    "location": "PPT/海外/DCIM",
    "updated": "2026-08-03"
  },
  {
    "id": "shared-38",
    "title": "CET-iMCM V4.0 Oct 2025 zh",
    "category": "演示材料",
    "format": "PPTX",
    "product": "通用",
    "language": "中文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/CET-iMCM V4.0 Oct 2025 zh.pptx",
    "location": "PPT/海外/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-39",
    "title": "DCIM Fcunction Introduce",
    "category": "演示材料",
    "format": "PPTX",
    "product": "DCIM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/DCIM Fcunction Introduce.pptx",
    "location": "PPT/海外/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-40",
    "title": "DCIM Info - 修正版本 Sep 2025 En(未完成 PDG DCIM交流搁置)",
    "category": "演示材料",
    "format": "PPTX",
    "product": "DCIM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCIM/DCIM Info - 修正版本 Sep 2025 En(未完成 PDG DCIM交流搁置).pptx",
    "location": "PPT/海外/DCIM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-41",
    "title": "CET DCOM platform EN Jun 2026",
    "category": "演示材料",
    "format": "PDF",
    "product": "DCOM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCOM/CET DCOM platform EN Jun 2026.pdf",
    "location": "PPT/海外/DCOM",
    "updated": "2026-07-28"
  },
  {
    "id": "shared-42",
    "title": "CET_DCOM_Intro EN Jun 2026",
    "category": "演示材料",
    "format": "PPTX",
    "product": "DCOM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCOM/CET_DCOM_Intro EN Jun 2026.pptx",
    "location": "PPT/海外/DCOM",
    "updated": "2026-06-09"
  },
  {
    "id": "shared-43",
    "title": "DCOM Info",
    "category": "演示材料",
    "format": "PDF",
    "product": "DCOM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCOM/DCOM Info.pdf",
    "location": "PPT/海外/DCOM",
    "updated": "2026-07-09"
  },
  {
    "id": "shared-44",
    "title": "DCOM Info",
    "category": "演示材料",
    "format": "PPTX",
    "product": "DCOM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/DCOM/DCOM Info.pptx",
    "location": "PPT/海外/DCOM",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-45",
    "title": "CET-DC DCIM+DCOM 2026 01 Aug",
    "category": "演示材料",
    "format": "PPTX",
    "product": "DCOM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/PPT/海外/整体/CET-DC DCIM+DCOM 2026 01 Aug.pptx",
    "location": "PPT/海外/整体",
    "updated": "2026-08-02"
  },
  {
    "id": "shared-46",
    "title": "软件问题回复记录汇总-0919",
    "category": "问答记录",
    "format": "XLSX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/Q&A/软件问题回复记录汇总-0919.xlsx",
    "location": "Q&A",
    "updated": "2026-08-07"
  },
  {
    "id": "shared-47",
    "title": "CET Software Product Roadmap",
    "category": "能力与路线图",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/其他资料roadmap等/CET Software Product Roadmap.pdf",
    "location": "其他资料roadmap等",
    "updated": "2026-08-06"
  },
  {
    "id": "shared-48",
    "title": "告警通知方式整理_20260813",
    "category": "能力与路线图",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/其他资料roadmap等/告警通知方式整理_20260813.pdf",
    "location": "其他资料roadmap等",
    "updated": "2026-08-13"
  },
  {
    "id": "shared-49",
    "title": "BA暖通监控系统功能列表",
    "category": "功能清单",
    "format": "XLSX",
    "product": "BA",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/国内/BA暖通监控系统功能列表.xlsx",
    "location": "功能列表/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-50",
    "title": "DCIM平台系统功能列表",
    "category": "功能清单",
    "format": "XLSX",
    "product": "DCIM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/国内/DCIM平台系统功能列表.xlsx",
    "location": "功能列表/国内",
    "updated": "2026-09-08"
  },
  {
    "id": "shared-51",
    "title": "一体化监控系统架构及功能描述",
    "category": "功能清单",
    "format": "XLSX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/国内/一体化监控系统架构及功能描述.xlsx",
    "location": "功能列表/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-52",
    "title": "动环监控系统架构及功能",
    "category": "功能清单",
    "format": "XLSX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/国内/动环监控系统架构及功能.xlsx",
    "location": "功能列表/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-53",
    "title": "CET BMS Catalog",
    "category": "功能清单",
    "format": "PDF",
    "product": "BMS",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/海外/CET BMS Catalog.pdf",
    "location": "功能列表/海外",
    "updated": "2026-09-16"
  },
  {
    "id": "shared-54",
    "title": "CET BMS Function List",
    "category": "功能清单",
    "format": "XLSX",
    "product": "BMS",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/海外/CET BMS Function List.xlsx",
    "location": "功能列表/海外",
    "updated": "2026-09-16"
  },
  {
    "id": "shared-55",
    "title": "CET CCCS Catalog",
    "category": "功能清单",
    "format": "PDF",
    "product": "CCCS",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/海外/CET CCCS Catalog.pdf",
    "location": "功能列表/海外",
    "updated": "2026-09-16"
  },
  {
    "id": "shared-56",
    "title": "CET CCCS Function List",
    "category": "功能清单",
    "format": "XLSX",
    "product": "CCCS",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/海外/CET CCCS Function List.xlsx",
    "location": "功能列表/海外",
    "updated": "2026-09-16"
  },
  {
    "id": "shared-57",
    "title": "CET DCOM Function List",
    "category": "功能清单",
    "format": "XLSX",
    "product": "DCOM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/海外/CET DCOM Function List.xlsx",
    "location": "功能列表/海外",
    "updated": "2026-09-16"
  },
  {
    "id": "shared-58",
    "title": "CET EPMS Catalog",
    "category": "功能清单",
    "format": "PDF",
    "product": "EPMS",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/海外/CET EPMS Catalog.pdf",
    "location": "功能列表/海外",
    "updated": "2026-09-16"
  },
  {
    "id": "shared-59",
    "title": "CET EPMS Function List",
    "category": "功能清单",
    "format": "XLSX",
    "product": "EPMS",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/海外/CET EPMS Function List.xlsx",
    "location": "功能列表/海外",
    "updated": "2026-09-16"
  },
  {
    "id": "shared-60",
    "title": "DCIM Platform Function List",
    "category": "功能清单",
    "format": "XLSX",
    "product": "DCIM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/海外/DCIM Platform Function List.xlsx",
    "location": "功能列表/海外",
    "updated": "2026-09-08"
  },
  {
    "id": "shared-61",
    "title": "DCIM平台系统功能列表 zh",
    "category": "功能清单",
    "format": "XLSX",
    "product": "DCIM",
    "language": "中文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/海外/DCIM平台系统功能列表 zh.xlsx",
    "location": "功能列表/海外",
    "updated": "2026-09-08"
  },
  {
    "id": "shared-62",
    "title": "Funciton and GUI",
    "category": "功能清单",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/海外/Funciton and GUI.docx",
    "location": "功能列表/海外",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-63",
    "title": "Funciton and GUI",
    "category": "功能清单",
    "format": "PDF",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/功能列表/海外/Funciton and GUI.pdf",
    "location": "功能列表/海外",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-64",
    "title": "DEMO Deployment Hardware Specifications",
    "category": "培训资料",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/Training Materials/Demo/DEMO Deployment Hardware Specifications.pdf",
    "location": "培训资料/Training Materials/Demo",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-65",
    "title": "BMS Software Architecture-Linux",
    "category": "培训资料",
    "format": "PDF",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/Training Materials/Instruction Manual/BMS Software Architecture-Linux.pdf",
    "location": "培训资料/Training Materials/Instruction Manual",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-66",
    "title": "BMS Software Architecture-Windows",
    "category": "培训资料",
    "format": "PDF",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/Training Materials/Instruction Manual/BMS Software Architecture-Windows.pdf",
    "location": "培训资料/Training Materials/Instruction Manual",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-67",
    "title": "PecStar Config  Graphic Editing",
    "category": "培训资料",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/Training Materials/Instruction Manual/PecStar Config  Graphic Editing.pdf",
    "location": "培训资料/Training Materials/Instruction Manual",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-68",
    "title": "PecStar Config  System Tuning",
    "category": "培训资料",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/Training Materials/Instruction Manual/PecStar Config  System Tuning.pdf",
    "location": "培训资料/Training Materials/Instruction Manual",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-69",
    "title": "PecStar_V4.0_R5_SP1 Windows Installation and Use Instructions",
    "category": "培训资料",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/Training Materials/Instruction Manual/PecStar_V4.0_R5_SP1 Windows Installation and Use Instructions.pdf",
    "location": "培训资料/Training Materials/Instruction Manual",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-70",
    "title": "【3-02】3.1 Software Deployment Instruction Manual",
    "category": "培训资料",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/Training Materials/Instruction Manual/【3-02】3.1 Software Deployment Instruction Manual.pdf",
    "location": "培训资料/Training Materials/Instruction Manual",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-71",
    "title": "CET Data Centre BMS Solution",
    "category": "培训资料",
    "format": "PPTX",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/Training Materials/PPT/CET Data Centre BMS Solution.pptx",
    "location": "培训资料/Training Materials/PPT",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-72",
    "title": "CET PecStar Introduction",
    "category": "培训资料",
    "format": "PPTX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/Training Materials/PPT/CET PecStar Introduction.pptx",
    "location": "培训资料/Training Materials/PPT",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-73",
    "title": "05 系统整定 en-US",
    "category": "培训资料",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/国内/05 系统整定 en-US.docx",
    "location": "培训资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-74",
    "title": "06 配置及数据服务 en-US",
    "category": "培训资料",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/国内/06 配置及数据服务 en-US.docx",
    "location": "培训资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-75",
    "title": "08 图形编辑 en-US(1)",
    "category": "培训资料",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/国内/08 图形编辑 en-US(1).docx",
    "location": "培训资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-76",
    "title": "PecStar-L软件宝典V10（20220415）",
    "category": "培训资料",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/国内/PecStar-L软件宝典V10（20220415）.docx",
    "location": "培训资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-77",
    "title": "PecStar_V4.0_R5_SP1 Windows新版安装使用说明 en-GB",
    "category": "培训资料",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/国内/PecStar_V4.0_R5_SP1 Windows新版安装使用说明 en-GB.docx",
    "location": "培训资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-78",
    "title": "linux一主一备架构说明",
    "category": "培训资料",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/国内/linux一主一备架构说明.docx",
    "location": "培训资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-79",
    "title": "【3-02】3.1版本软件部署指导手册及注意事项20240315 en-GB-完成版本",
    "category": "培训资料",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/国内/【3-02】3.1版本软件部署指导手册及注意事项20240315 en-GB-完成版本.docx",
    "location": "培训资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-80",
    "title": "数据中心Windows部署模式介绍 en-US",
    "category": "培训资料",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/国内/数据中心Windows部署模式介绍 en-US.docx",
    "location": "培训资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-81",
    "title": "数据中心Windows部署模式介绍",
    "category": "培训资料",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/国内/数据中心Windows部署模式介绍.docx",
    "location": "培训资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-82",
    "title": "数据中心一主两备架构说明",
    "category": "培训资料",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/培训资料/国内/数据中心一主两备架构说明.docx",
    "location": "培训资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-83",
    "title": "GUI",
    "category": "演示材料",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/截图 & video/页面截图/web/DCIM/成品形式的截图文件/GUI.docx",
    "location": "截图 & video/页面截图/web/DCIM/成品形式的截图文件",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-84",
    "title": "GUI",
    "category": "演示材料",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/截图 & video/页面截图/web/DCIM/成品形式的截图文件/GUI.pdf",
    "location": "截图 & video/页面截图/web/DCIM/成品形式的截图文件",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-85",
    "title": "电池监控系统截图",
    "category": "演示材料",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/截图 & video/页面截图/web/DCIM/成品形式的截图文件/电池监控系统截图.docx",
    "location": "截图 & video/页面截图/web/DCIM/成品形式的截图文件",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-86",
    "title": "LDAP SSO",
    "category": "技术方案",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/技术说明资料/国内/LDAP SSO.docx",
    "location": "技术说明资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-87",
    "title": "N+2 Architecture",
    "category": "技术方案",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/技术说明资料/国内/N+2 Architecture.docx",
    "location": "技术说明资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-88",
    "title": "数据中心3+3集群方案设计文档",
    "category": "技术方案",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/技术说明资料/国内/数据中心3+3集群方案设计文档.docx",
    "location": "技术说明资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-89",
    "title": "数据中心Windows部署模式介绍",
    "category": "技术方案",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/技术说明资料/国内/数据中心Windows部署模式介绍.pdf",
    "location": "技术说明资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-90",
    "title": "数据中心一主两备架构说明",
    "category": "技术方案",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/技术说明资料/国内/数据中心一主两备架构说明.docx",
    "location": "技术说明资料/国内",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-91",
    "title": "赵红光-服务器信息",
    "category": "技术方案",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/技术说明资料/国内/赵红光-服务器信息.docx",
    "location": "技术说明资料/国内",
    "updated": "2026-09-09"
  },
  {
    "id": "shared-92",
    "title": "2023-01-18_CET_OPCUAServer_Certificate",
    "category": "技术方案",
    "format": "PDF",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/技术说明资料/海外/2023-01-18_CET_OPCUAServer_Certificate.pdf",
    "location": "技术说明资料/海外",
    "updated": "2026-06-23"
  },
  {
    "id": "shared-93",
    "title": "BMS Software Architecture-Linux",
    "category": "技术方案",
    "format": "PDF",
    "product": "BMS",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/技术说明资料/海外/BMS Software Architecture-Linux.pdf",
    "location": "技术说明资料/海外",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-94",
    "title": "BMS Software Architecture-Windows",
    "category": "技术方案",
    "format": "PDF",
    "product": "BMS",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/技术说明资料/海外/BMS Software Architecture-Windows.pdf",
    "location": "技术说明资料/海外",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-95",
    "title": "Description of N+2 Architecture",
    "category": "技术方案",
    "format": "PDF",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/技术说明资料/海外/Description of N+2 Architecture.pdf",
    "location": "技术说明资料/海外",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-96",
    "title": "LDAP SSO",
    "category": "技术方案",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/技术说明资料/海外/LDAP SSO.docx",
    "location": "技术说明资料/海外",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-97",
    "title": "CET Electric Technology Inc.(XCETCB00EV1)",
    "category": "产品介绍",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/整体宣传资料 by 市场/CET Electric Technology Inc.(XCETCB00EV1).pdf",
    "location": "整体宣传资料 by 市场",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-98",
    "title": "英文-宣传册",
    "category": "产品介绍",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/整体宣传资料 by 市场/英文-宣传册.pdf",
    "location": "整体宣传资料 by 市场",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-99",
    "title": "CET BMS vs Schneider EBO v1.0",
    "category": "竞品分析",
    "format": "PDF",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/BMS/CET BMS vs Schneider EBO v1.0.pdf",
    "location": "竞品分析内容/BMS",
    "updated": "2026-09-07"
  },
  {
    "id": "shared-100",
    "title": "CET BMS vs Schneider EBO",
    "category": "竞品分析",
    "format": "PDF",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/BMS/CET BMS vs Schneider EBO.pdf",
    "location": "竞品分析内容/BMS",
    "updated": "2026-09-02"
  },
  {
    "id": "shared-101",
    "title": "CET_BMS_vs_EBO",
    "category": "竞品分析",
    "format": "XLSX",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/BMS/CET_BMS_vs_EBO.xlsx",
    "location": "竞品分析内容/BMS",
    "updated": "2026-09-07"
  },
  {
    "id": "shared-102",
    "title": "CET_BMS_vs_EBO_备份_20260907",
    "category": "竞品分析",
    "format": "XLSX",
    "product": "BMS",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/BMS/CET_BMS_vs_EBO_备份_20260907.xlsx",
    "location": "竞品分析内容/BMS",
    "updated": "2026-09-02"
  },
  {
    "id": "shared-103",
    "title": "CET vs Competitors_Data Center Software Comparison",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET vs Competitors_Data Center Software Comparison.pdf",
    "location": "竞品分析内容/DCIM",
    "updated": "2026-08-03"
  },
  {
    "id": "shared-104",
    "title": "CET vs Schneider_Data Center Software Comparison",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET vs Schneider_Data Center Software Comparison.pdf",
    "location": "竞品分析内容/DCIM",
    "updated": "2026-08-04"
  },
  {
    "id": "shared-105",
    "title": "ETAP_Product_Overview",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/ETAP/官方文档/ETAP_Product_Overview.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/ETAP/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-106",
    "title": "ETAP_Solutions_Overview",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/ETAP/官方文档/ETAP_Solutions_Overview.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/ETAP/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-107",
    "title": "NetBotz_750_Brochure",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Schneider_Electric/官方文档/NetBotz_750_Brochure.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Schneider_Electric/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-108",
    "title": "NetBotz_750_Datasheet",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Schneider_Electric/官方文档/NetBotz_750_Datasheet.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Schneider_Electric/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-109",
    "title": "PME_2023_System_Guide",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Schneider_Electric/官方文档/PME_2023_System_Guide.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Schneider_Electric/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-110",
    "title": "Schneider_DCIM_software_for_data_centers",
    "category": "竞品分析",
    "format": "PDF",
    "product": "DCIM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Schneider_Electric/官方文档/Schneider_DCIM_software_for_data_centers.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Schneider_Electric/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-111",
    "title": "Power_IQ_FAQ_7_0",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Sunbird/官方文档/Power_IQ_FAQ_7_0.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Sunbird/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-112",
    "title": "Environet_Alert_Guide_Specifications_SL-70615",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Vertiv/官方文档/Environet_Alert_Guide_Specifications_SL-70615.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Vertiv/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-113",
    "title": "Environet_Alert_User_Manual",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Vertiv/官方文档/Environet_Alert_User_Manual.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Vertiv/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-114",
    "title": "Power_Insight_v3_User_Manual",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Vertiv/官方文档/Power_Insight_v3_User_Manual.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/01_国际竞品/Vertiv/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-115",
    "title": "NetEco6000_Brochure_CN",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "中文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/02_国内竞品/Huawei/官方文档/NetEco6000_Brochure_CN.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/02_国内竞品/Huawei/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-116",
    "title": "NetEco6000_Brochure_EN",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/02_国内竞品/Huawei/官方文档/NetEco6000_Brochure_EN.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research/02_国内竞品/Huawei/官方文档",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-117",
    "title": "ETAP_PSMS_Factsheet_2024",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/ETAP/官方资料/ETAP_PSMS_Factsheet_2024.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/ETAP/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-118",
    "title": "ETAP_Product_Overview",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/ETAP/官方资料/ETAP_Product_Overview.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/ETAP/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-119",
    "title": "ETAP_Real_Time_Overview",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/ETAP/官方资料/ETAP_Real_Time_Overview.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/ETAP/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-120",
    "title": "ETAP_Solutions_Overview",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/ETAP/官方资料/ETAP_Solutions_Overview.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/ETAP/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-121",
    "title": "Ignition_IIoT_Architecture",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Ignition/官方资料/Ignition_IIoT_Architecture.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Ignition/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-122",
    "title": "JCI_Data_Center_Controls_Solutions_NA",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Johnson_Controls/官方资料/JCI_Data_Center_Controls_Solutions_NA.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Johnson_Controls/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-123",
    "title": "NetBotz_750_Brochure",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Schneider_Electric/官方资料/NetBotz_750_Brochure.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Schneider_Electric/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-124",
    "title": "NetBotz_750_Datasheet",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Schneider_Electric/官方资料/NetBotz_750_Datasheet.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Schneider_Electric/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-125",
    "title": "PME_2023_System_Guide",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Schneider_Electric/官方资料/PME_2023_System_Guide.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Schneider_Electric/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-126",
    "title": "Schneider_DCIM_software_for_data_centers",
    "category": "竞品分析",
    "format": "PDF",
    "product": "DCIM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Schneider_Electric/官方资料/Schneider_DCIM_software_for_data_centers.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Schneider_Electric/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-127",
    "title": "Building_X_Operations_Manager_2026_Datasheet",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Siemens/官方资料/Building_X_Operations_Manager_2026_Datasheet.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Siemens/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-128",
    "title": "Environet_Alert_Guide_Specifications_SL-70615",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Vertiv/官方资料/Environet_Alert_Guide_Specifications_SL-70615.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Vertiv/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-129",
    "title": "Environet_Alert_User_Manual",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Vertiv/官方资料/Environet_Alert_User_Manual.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Vertiv/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-130",
    "title": "Power_Insight_v3_User_Manual",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Vertiv/官方资料/Power_Insight_v3_User_Manual.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Vertiv/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-131",
    "title": "Vertiv_Unify_Brochure_AV-50007",
    "category": "竞品分析",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Vertiv/官方资料/Vertiv_Unify_Brochure_AV-50007.pdf",
    "location": "竞品分析内容/DCIM/CET_DCIM_BMS_Competitor_Research_V2/01_国际竞品/Vertiv/官方资料",
    "updated": "2026-07-29"
  },
  {
    "id": "shared-132",
    "title": "CET DCOM vs EcoStruxure IT (module suite) vs Siemens (Desigo CC + Clarity LC) Aug 2026",
    "category": "竞品分析",
    "format": "PDF",
    "product": "DCOM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCOM/CET DCOM vs EcoStruxure IT (module suite) vs Siemens (Desigo CC + Clarity LC) Aug 2026.pdf",
    "location": "竞品分析内容/DCOM",
    "updated": "2026-08-17"
  },
  {
    "id": "shared-133",
    "title": "DCOM_vs_EcoStruxureIT_vs_Siemens_对比表_客户版_CN_EN_2026-08_v5",
    "category": "竞品分析",
    "format": "XLSX",
    "product": "DCOM",
    "language": "中文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCOM/DCOM_vs_EcoStruxureIT_vs_Siemens_对比表_客户版_CN_EN_2026-08_v5.xlsx",
    "location": "竞品分析内容/DCOM",
    "updated": "2026-08-17"
  },
  {
    "id": "shared-134",
    "title": "DCOM_vs_EcoStruxure_IT_Advisor_对比表_客户版_CN_EN",
    "category": "竞品分析",
    "format": "XLSX",
    "product": "DCOM",
    "language": "中文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/竞品分析内容/DCOM/DCOM_vs_EcoStruxure_IT_Advisor_对比表_客户版_CN_EN.xlsx",
    "location": "竞品分析内容/DCOM",
    "updated": "2026-08-11"
  },
  {
    "id": "shared-135",
    "title": "DCIM系统介绍稿",
    "category": "演示材料",
    "format": "DOCX",
    "product": "DCIM",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/系统介绍/DCIM系统介绍稿.docx",
    "location": "系统介绍",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-136",
    "title": "V4.0介绍稿子",
    "category": "演示材料",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/系统介绍/V4.0介绍稿子.docx",
    "location": "系统介绍",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-137",
    "title": "软件演示脚本",
    "category": "演示材料",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/系统介绍/软件演示脚本.docx",
    "location": "系统介绍",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-149",
    "title": "数据中心软件产品调试手册（用服版）V1.0",
    "category": "操作手册",
    "format": "DOCX",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/国内/数据中心/数据中心软件产品调试手册（用服版）V1.0.docx",
    "location": "软件功能操作文档/国内/数据中心",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-150",
    "title": "05 系统整定",
    "category": "操作手册",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/国内/数据中心/软件后台配置/05 系统整定.pdf",
    "location": "软件功能操作文档/国内/数据中心/软件后台配置",
    "updated": "2026-08-14"
  },
  {
    "id": "shared-151",
    "title": "06 配置及数据服务",
    "category": "操作手册",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/国内/数据中心/软件后台配置/06 配置及数据服务.pdf",
    "location": "软件功能操作文档/国内/数据中心/软件后台配置",
    "updated": "2026-08-14"
  },
  {
    "id": "shared-152",
    "title": "07 前台通信管理",
    "category": "操作手册",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/国内/数据中心/软件后台配置/07 前台通信管理.pdf",
    "location": "软件功能操作文档/国内/数据中心/软件后台配置",
    "updated": "2026-08-14"
  },
  {
    "id": "shared-153",
    "title": "08 图形编辑",
    "category": "操作手册",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/国内/数据中心/软件后台配置/08 图形编辑.pdf",
    "location": "软件功能操作文档/国内/数据中心/软件后台配置",
    "updated": "2026-08-14"
  },
  {
    "id": "shared-154",
    "title": "09 实时监控",
    "category": "操作手册",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/国内/数据中心/软件后台配置/09 实时监控.pdf",
    "location": "软件功能操作文档/国内/数据中心/软件后台配置",
    "updated": "2026-08-14"
  },
  {
    "id": "shared-155",
    "title": "11 报表制作与查看",
    "category": "操作手册",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/国内/数据中心/软件后台配置/11 报表制作与查看.pdf",
    "location": "软件功能操作文档/国内/数据中心/软件后台配置",
    "updated": "2026-08-14"
  },
  {
    "id": "shared-156",
    "title": "13 趋势曲线分析",
    "category": "操作手册",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/国内/数据中心/软件后台配置/13 趋势曲线分析.pdf",
    "location": "软件功能操作文档/国内/数据中心/软件后台配置",
    "updated": "2026-08-14"
  },
  {
    "id": "shared-157",
    "title": "14 后台监控",
    "category": "操作手册",
    "format": "PDF",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/国内/数据中心/软件后台配置/14 后台监控.pdf",
    "location": "软件功能操作文档/国内/数据中心/软件后台配置",
    "updated": "2026-08-14"
  },
  {
    "id": "shared-158",
    "title": "CET BMS User Manual-V2.0-English-20251027",
    "category": "操作手册",
    "format": "PDF",
    "product": "BMS",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/CET BMS User Manual-V2.0-English-20251027.pdf",
    "location": "软件功能操作文档/海外",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-159",
    "title": "CET CPOS User Manual-V1.0-English-20240308",
    "category": "操作手册",
    "format": "PDF",
    "product": "CPOS",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/CET CPOS User Manual-V1.0-English-20240308.pdf",
    "location": "软件功能操作文档/海外",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-160",
    "title": "DCOM_User_Manual_EN_V1.0",
    "category": "操作手册",
    "format": "PDF",
    "product": "DCOM",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/DCOM_User_Manual_EN_V1.0.pdf",
    "location": "软件功能操作文档/海外",
    "updated": "2026-08-31"
  },
  {
    "id": "shared-161",
    "title": "High Availability Solution and Primary-Secondary Failover Mechanism Description",
    "category": "操作手册",
    "format": "PDF",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/High Availability Solution and Primary-Secondary Failover Mechanism Description.pdf",
    "location": "软件功能操作文档/海外",
    "updated": "2026-06-11"
  },
  {
    "id": "shared-162",
    "title": "PecStar Config  Graphic Editing",
    "category": "操作手册",
    "format": "PDF",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/PecStar Config  Graphic Editing.pdf",
    "location": "软件功能操作文档/海外",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-163",
    "title": "Section 6.1.1 System Brief",
    "category": "操作手册",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/SOP/PDG/Section 6.1.1 System Brief.docx",
    "location": "软件功能操作文档/海外/SOP/PDG",
    "updated": "2026-08-03"
  },
  {
    "id": "shared-164",
    "title": "Section 6.1.4 System Operating Procedures20241202",
    "category": "操作手册",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/SOP/PDG/Section 6.1.4 System Operating Procedures20241202.docx",
    "location": "软件功能操作文档/海外/SOP/PDG",
    "updated": "2026-08-03"
  },
  {
    "id": "shared-165",
    "title": "Section 6.1.5 Operation Procedures",
    "category": "操作手册",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/SOP/PDG/Section 6.1.5 Operation Procedures.docx",
    "location": "软件功能操作文档/海外/SOP/PDG",
    "updated": "2026-08-03"
  },
  {
    "id": "shared-166",
    "title": "Section 6.2.5 Operation Manual",
    "category": "操作手册",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/SOP/PDG/Section 6.2.5 Operation Manual.docx",
    "location": "软件功能操作文档/海外/SOP/PDG",
    "updated": "2026-08-03"
  },
  {
    "id": "shared-167",
    "title": "【3-02】3.1 Software Deployment Instruction Manual",
    "category": "操作手册",
    "format": "PDF",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/【3-02】3.1 Software Deployment Instruction Manual.pdf",
    "location": "软件功能操作文档/海外",
    "updated": "2026-06-07"
  },
  {
    "id": "shared-168",
    "title": "【3-04】海外版本软件使用手册202607027",
    "category": "操作手册",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/【3-04】海外版本软件使用手册202607027.docx",
    "location": "软件功能操作文档/海外",
    "updated": "2026-08-12"
  },
  {
    "id": "shared-169",
    "title": "【3-04】海外版本软件使用手册202607031",
    "category": "操作手册",
    "format": "DOCX",
    "product": "通用",
    "language": "英文",
    "path": "/Users/a48750/Desktop/数据中心海外资料/标准版宣传资料/软件功能操作文档/海外/【3-04】海外版本软件使用手册202607031.docx",
    "location": "软件功能操作文档/海外",
    "updated": "2026-07-31"
  },
  {
    "id": "template-0",
    "title": "01-需求访谈记录模板",
    "category": "工件模板",
    "format": "MD",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/AA工作台/售前Agent/工件模板/01-需求访谈记录模板.md",
    "location": "售前Agent / 工件模板",
    "updated": "2026-09-22"
  },
  {
    "id": "template-1",
    "title": "02-前期调研台账模板",
    "category": "工件模板",
    "format": "MD",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/AA工作台/售前Agent/工件模板/02-前期调研台账模板.md",
    "location": "售前Agent / 工件模板",
    "updated": "2026-09-22"
  },
  {
    "id": "template-2",
    "title": "03-项目目标确认记录模板",
    "category": "工件模板",
    "format": "MD",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/AA工作台/售前Agent/工件模板/03-项目目标确认记录模板.md",
    "location": "售前Agent / 工件模板",
    "updated": "2026-09-22"
  },
  {
    "id": "template-3",
    "title": "04-开工会议纪要模板",
    "category": "工件模板",
    "format": "MD",
    "product": "通用",
    "language": "未标注",
    "path": "/Users/a48750/Desktop/AA工作台/售前Agent/工件模板/04-开工会议纪要模板.md",
    "location": "售前Agent / 工件模板",
    "updated": "2026-09-22"
  }
];
